/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface FeaturesFlag {
  regenerator: boolean
  functionName: boolean
  newTarget: boolean
  objectSuper: boolean
  typeofSymbol: boolean
  forOf: boolean
  classes: boolean
  spread: boolean
  classProperties: boolean
  destructuring: boolean
  computedProperties: boolean
  shorthandProperties: boolean
  stickyRegex: boolean
  templateLiterals: boolean
  parameters: boolean
  arrowFunctions: boolean
  blockScoping: boolean
  exponentiationOperator: boolean
  classStaticBlock: boolean
  privateMethods: boolean
  asyncToGenerator: boolean
  logicalAssignmentOperators: boolean
  nullishCoalescing: boolean
  objectRestSpread: boolean
  optionalChaining: boolean
  optionalCatchBinding: boolean
}
export interface Line {
  l: number
  c: number
}
export interface Detail {
  feature: string
  s: number
  e: number
  ls: Line
  le: Line
}
export interface ParseOptions {
  target?: string
  browserslist: string
  filename: string
  code: string
}
export interface DetectResult {
  features: FeaturesFlag
  esVersions: Record<string, boolean>
  details: Array<Detail>
}
export function detect(options: ParseOptions): DetectResult
export interface LookupOptions {
  filename: string
  details: Array<Detail>
}
export interface LookupResult {
  ls?: Line
  le?: Line
  source?: string
}
export function lookup(options: LookupOptions): Array<LookupResult>
